#!/usr/bin/env python3
"""Generate docs/rules.md from RULE_CATALOG.

Run via:
    mise run gen-rules-doc
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow running from any working directory.
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "src"))

from jarify.rules import RULE_CATALOG  # noqa: E402

_HEADER = """\
<!-- Auto-generated by `mise run gen-rules-doc` — do not edit by hand. -->
# Jarify Rule Reference

Complete list of built-in jarify rules. For style guidance and bad/good SQL
examples see [`sql-style-guide.md`](sql-style-guide.md).

## Understanding the table

| Column | Meaning |
|--------|---------|
| **Rule** | Kebab-case identifier. Use this in `-- jarify: disable-next-line <rule>` directives. |
| **Config key** | Key in `jarify.toml` under `[jarify]`. Both `snake_case` and `kebab-case` forms are accepted. |
| **Default** | `on` = always active; `off` = disabled; `warn` / `error` = active at that severity. |
| **Auto-fix** | `yes` = `jarify fmt` rewrites the violation automatically; `no` = lint only. |

## Rules

| Rule | Config key | Default | Auto-fix | Description |
|------|-----------|---------|---------|-------------|
"""

_FOOTER = """
## Configuring rules

Severity values: `"off"` · `"warn"` · `"error"`. Boolean flags accept `true` / `false`.

Both `snake_case` and `kebab-case` key forms are accepted in `jarify.toml`:

```toml
[jarify]
# snake_case (traditional)
no_select_star         = "error"
prefer-if-over-case    = "off"   # kebab-case also works

# silence a rule entirely
no_unused_cte          = "off"
```

## Disable directives

Suppress a rule for a single statement with an inline comment:

```sql
SELECT *  -- jarify: disable-next-line no-select-star
FROM my_table
;
```

Run `jarify rules` to print this table in your terminal, or
`jarify rules --format json` for a machine-readable list suitable for
editor integrations (e.g. LSP completion for disable directives).
"""


def generate() -> str:
    rows = [
        f"| `{r.name}` | `{r.config_key}` | {r.default} | {'yes' if r.auto_fix else 'no'} | {r.description} |"
        for r in RULE_CATALOG
    ]
    return _HEADER + "\n".join(rows) + "\n" + _FOOTER


def main() -> None:
    content = generate()
    out = ROOT / "docs" / "rules.md"
    out.write_text(content)
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
